### ISSUE TITLE
i8 values can be saved at the stack in 8bit alligenment

### ISSUE THREAD

**Issue by ghost** [llvm-dcpu16/llvm-dcpu16#104]
i8 values are not allignent to 16bit and can break the ASM code. (Right now the ASM Printer)

**Comment by ghost** [comment]
We should (re-)insert the default alignment for i8 types and for the stack (16bit alignment).

**Comment by krasin** [comment]
If I understand correctly, it's the Clang bug, right?

**Comment by ghost** [comment]
And a LLVM Bug, I will fix the LLVM bug in the next PR.

**Comment by krasin** [comment]
Could you please provide an llvm assembly program that should work fine, but fails now?

**Comment by ghost** [comment]
That's odd, I can't. I even tried to go back in branch-history if some patched fixed it, but it doesn't seem that way. But non the less: We need to update the datalayout in llvm and clang:

DataLayout("e-p:16:16:16-i8:16:16-i16:16:16-i32:16:32-s0:16:16-n16")

Seems most sane. Everything is at least aligned at 16bit and we only support native i16 datatypes.
http://llvm.org/docs/LangRef.html#datalayout

**Comment by krasin** [comment]
Looks fine.

I am going to bed soon. Tomorrow I will merge both (LLVM and Clang) trees with the upstream and fix as many trivial things as possible (like datalayout).

After that, I might have time to look at our xfail tests.

**Comment by ghost** [comment]
Fixed by ad0222fc025312f323038f2dfcf9785aa53c870e
