### ISSUE TITLE
Signed arithmetic is broken

### ISSUE THREAD

**Issue by krasin** [llvm-dcpu16/llvm-dcpu16#107]
Currently, we handle signed types as unsigned. We'll need to fix that eventually, but first, let's wait for updates of DCPU16 specs.

**Comment by ghost** [comment]
Partly fixed by 258221b195acbd1b4e8a28b15daaf5989e771bb7

IF conditions still needs to be fixed.

**Comment by ghost** [comment]
Fixed by 70446522175ea11f78e64544b7460abadfbe0534
