### ISSUE TITLE
Migration of repo to llvm-dcpu16 organization

### ISSUE THREAD

**Issue by krasin** [llvm-dcpu16/llvm-dcpu16#110]
It turns out that having this repository under my personal account makes some troubles. For example, if I push a branch with some feature, every new fork gets this branch, even though it's pretty much through-away branch (once it's merged with dcpu16 branch).

Also, the project is now a true collaboration among several programmers, I can't say that I'm the primary committer (although, I have a hope to make a good progress on this weekend).

So, the project has moved to llvm-dcpu16 organization and my personal repository has now a fork.

**Comment by ghost** [comment]
Closed, since the move has been done.
