### ISSUE TITLE
Integrate Clang with nos_linker

### ISSUE THREAD

**Issue by krasin** [llvm-dcpu16/llvm-dcpu16#112]
To make the development with DCPU16 Clang easier, we need to move from the scheme:

```
clang -ccc-host-triple dcpu16 -S foo.c
clang -ccc-host-triple dcpu16 -S bar.c
nos_linker -o image.dcpu16 foo.s bar.s
```

to the shorter scheme:

```
clang -ccc-host-triple dcpu16 foo.c bar.c -o image.dcpu16
```

**Comment by ghost** [comment]
An example script CMAKE script for a project will also be nice.

**Comment by krasin** [comment]
I agree. #115

**Comment by ghost** [comment]
I don't think that this is still a valid issue since binutils arrived. Please re-open when you have a different opinion.
