### ISSUE TITLE
Add examples to SDK

### ISSUE THREAD

**Issue by krasin** [llvm-dcpu16/llvm-dcpu16#115]
SDK should contain examples (for example, with CMAKE build scripts) to make users life easier

**Comment by ghost** [comment]
We have a very simple build script right now, which builds a SDK with a very simple makefile based c project. The repository to the example files is:
https://github.com/llvm-dcpu16/simple-example

The build script can be found under:
https://github.com/downloads/llvm-dcpu16/llvm-dcpu16/build-sdk.sh
