### ISSUE TITLE
Implement&write tests for more variants of shifts

### ISSUE THREAD

**Issue by krasin** [llvm-dcpu16/llvm-dcpu16#119]
Currently, on register and immediate operands are supported. See #118.

**Comment by ghost** [comment]
Fixed with fded63c153f356f30b04b2b1225f9afcdd0182a7

**Comment by krasin** [comment]
Do we have tests for this issue? If not, I would reopen it.

**Comment by ghost** [comment]
You just wrote the patch yourself .... 

If you want to add further tests, okay, but don't open a issue when there is none.

**Comment by krasin** [comment]
> You just wrote the patch yourself ....

It was kind of a rhetorical question. Sorry for not being clear.

ok, I have filed #124 and will fix it soon.

**Comment by ghost** [comment]
Sorry, just monday morning and I need to go to work soon. ;)

**Comment by krasin** [comment]
np ;)
