### ISSUE TITLE
Implement arithmetic shift and signed comparisons once Notch updates the spec

### ISSUE THREAD

**Issue by Blei** [llvm-dcpu16/llvm-dcpu16#120]
Added an issue so it won't be forgotten.

**Comment by ghost** [comment]
Partly fixed by 258221b195acbd1b4e8a28b15daaf5989e771bb7.

Signed comparisons still needs to be fixed.

**Comment by ghost** [comment]
Signed comparisons fixed by 70446522175ea11f78e64544b7460abadfbe0534
