### ISSUE TITLE
Incorrect handling of bit fields

### ISSUE THREAD

**Issue by Blei** [llvm-dcpu16/llvm-dcpu16#136]
I'm not sure if this is a bug in the LLVM or Clang part. Probably both.

The following program:

``` c
typedef struct {
  unsigned lo : 8;
  unsigned hi : 8;
} fake_char;

fake_char add_fake_char(fake_char *a, fake_char *b) {
  fake_char res;
  res.hi = a->hi + b->hi;
  res.lo = a->lo + b->lo;
  return res;
}
```

produces the following error when compiled with -O1 or higher:

```
fatal error: error in backend: Cannot select: 0x55a7f50: ch = store 0x55a6c90, 0x55a6a90,
      0x55a6190, 0x55a6790<ST1[%5], trunc to i8> [ID=12]
```

The produced LLVM assembly seems incorrect (-O1 -emit-llvm):

```
%struct.fake_char = type { i8 }

define void @add_fake_char(%struct.fake_char* noalias nocapture sret %agg.result, %struct.fake_char* nocapture %a, %struct.fake_char* nocapture %b) nounwind {
entry:
  %0 = bitcast %struct.fake_char* %a to i16*
  %1 = load i16* %0, align 1
  %2 = bitcast %struct.fake_char* %b to i16*
  %3 = load i16* %2, align 1
  %add4 = add nsw i16 %3, %1
  %4 = trunc i16 %add4 to i8
  %5 = getelementptr inbounds %struct.fake_char* %agg.result, i16 0, i32 0
  store i8 %4, i8* %5, align 1
  ret void
}
```

Notice that the `fake_char` struct is incorrect; it should be `type { i8, i8, [2 x i8] }` (tested using the x86 backend).

**Comment by krasin** [comment]
Although, that's an issue, I'm wondering, are bit-fields wildly used or it's a minor feature?

**Comment by Blei** [comment]
It is probably a minor feature, but I thought it might come in handy when implementing stuff in a constrained memory environment. On the other hand, all that shifting and and-ing when handling bitfields might blow up the code too much anyways.

But more importantly, this bug shows that there are still errors in our implementation. I'm guessing related to the 16bit bytes, as this is a pretty fundamental change.

**Comment by krasin** [comment]
I agree

**Comment by krasin** [comment]
@Blei Thanks for fixing this!
