### ISSUE TITLE
Implementing the changes from DCPU16 RC1

### ISSUE THREAD

**Issue by ghost** [llvm-dcpu16/llvm-dcpu16#147]
FYA: http://dcpu.com/highnerd/rc_1/

TODO:
- Rename Instruction for carry substraction to SBX
- Implement new IF conditions

**Comment by ghost** [comment]
FYA: http://dcpu.com/highnerd/dcpu16_1_5.txt
- Added MDI (signed MOD)

**Comment by ghost** [comment]
Would this mapping be allright?

UREM (LLVM) -> MOD  (DCPU)
SREM (LLVM) -> MDI  (DCPU) 

http://llvm.org/docs/LangRef.html#i_urem

**Comment by Blei** [comment]
Notch doesn't actually specify whether MDI is a remainder or a modulo (see description on SREM). Also, what does `rounds towards 0` mean for a modulo operation?

Edit: on the other hand, we can probably assume he uses the Java `%` operator, which implements a remainder. So that should be ok.

**Comment by ghost** [comment]
I opened a question in the reddit thread, hopefully notch will answer.
http://www.reddit.com/r/dcpu16/comments/stf82/rfe_dcpu16_v15/c4guida

**Comment by ghost** [comment]
@Blei Yes, let's assume that he used the Java `%` operator and implement it the way I have recommended it.

Edit: Notch just answered my question. MDI is a remainder.

**Comment by ghost** [comment]
Fixed by commit 3e27d971ba408ca14b177f747a9dcee467ffddbe and 70446522175ea11f78e64544b7460abadfbe0534
