### ISSUE TITLE
Find a way to use IFB and IFC

### ISSUE THREAD

**Issue by Blei** [llvm-dcpu16/llvm-dcpu16#150]
Low priority issue IMO.

Currently these two instructions are not used. It would be great if we were able to write an optimization pass (peephole pattern? Not sure what's appropriate here) to check for

``` dasm
AND A, B
IFE A, 0
```

and similar and transform them to use `IFB` or `IFC`.

**Comment by CJKay** [comment]
We have a bit of a problem in that, with -O0 at least, LLVM tends to push the value of A after the AND and before the IFE jumps. It then pushes A back off the stack at each branch. I have a peephole optimsation pass in my fork (branch peephole-opts) but as soon as you start using the variable that was ANDed before the IF*, it does some weird stuff.

I suppose this isn't much of a problem as it is an annoyance. The chances that we'd ever see this optimisation in compiled code are pretty slim.

**Comment by Blei** [comment]
Implemented by #175. Thanks @CJKay!
