### ISSUE TITLE
Respect DCPU16 v1.7

### ISSUE THREAD

**Issue by ghost** [llvm-dcpu16/llvm-dcpu16#152]
http://www.reddit.com/r/dcpu16/comments/sv4bv/dcpu16_17/
- Made SHR, ASR, SHL a lot cheaper to encourage tricksy bit shifting. Yes, a cpu from the 80's has a barrel shifter, what of it?
- Removed IAP
- Updated interrupt behavior. Interrupts automatically turn on queueing now
- Added RFI, which turns off queueing, pops a and pops PC, all in one single instruction
- Because of the interrupt queueing, removed the callback to hardware when IA is 0. If the hardware is super curious, it can check the IA register itself.

As far as I can see, there's nothing much we must/can do. Only the shifting is interesting, since NOW it's good to actually do a shift rather then a division when we have a power of two. (DVI/DIV = 3c, ASR,SHL,SHR = 1c)

**Comment by krasin** [comment]
> As far as I can see, there's nothing much we must/can do.

RFI existed in MSP430, we deleted it. Also, MSP430 has a special calling convention for interrupts. We may resurrect/adopt part of that.

**Comment by ghost** [comment]
Really? I can't find those right now. Also, I have to admit that I never worked with interrupts before.

**Comment by krasin** [comment]
Yes, see 9a7fe3d9eab3eb65d3f9eff9ad3b75e6cb7bba4d

I have also used interrupts only in the educational goals before.

**Comment by Blei** [comment]
About the shifting vs. div: shifting is only cheaper in the unsigned case, as the shift and add and shift again sequence in the signed case takes 4+ instructions which is again slower than a `DVI`. Is there a flag to enable this optimization only for the unsigned case?

**Comment by Blei** [comment]
Nvm, it already works as hoped: signed div by 2 is `DVI`, unsigned is `SHR`. I think this can be closed unless notch ups the cost for `DVI` some more.

Edit: by 'this' I mean the shift vs. div issue, not the interrupts.

**Comment by ghost** [comment]
@krasin About interrupts: Is there any LLVM IR we can map those instructions against? If not, there's not much use for us to implement those.

The way I see it, the libc will need to implements the interrup / hardware handling with the help of the inline-asm.

**Comment by ghost** [comment]
BTW: llvm can be awesome at times.

**Comment by Blei** [comment]
@arbaal I think reverting the commit that was pointed out by krasin and updating some of the code, should pretty much solve interrupt handlers. I might look into this later today.

**Comment by ghost** [comment]
@Blei Sure! But you need to explain me in an example how to actually use that code then ;)

**Comment by Blei** [comment]
Yeah, you're right. Setting the active interrupt handler, sending interrupts and enabling/disabling queueing will have to be done throught asm :S At least the interrupt handlers' calling convention can be solved by llvm/clang though.

**Comment by ghost** [comment]
Interrupts fixed by f87cee324cb616bf608f9e4f0d5895e55a86f9b0
