### ISSUE TITLE
Assertion failed: (!TI->readsRegister(SrcReg) && "Terminator instructions cannot use virtual registers unless" "they are the first terminator in a block!"), function LowerAtomicPHINode, file /Users/andy/git/llvm-dcpu16/lib/CodeGen/PHIElimination.cpp, line

### ISSUE THREAD

**Issue by a1k0n** [llvm-dcpu16/llvm-dcpu16#191]
I haven't tracked this one down at all.  But the offending LLVM bitcode is crash1.ll in https://github.com/a1k0n/tetris-dcpu16/tree/llvm-crash

**Comment by Blei** [comment]
[LLVMdev thread about the issue](http://lists.cs.uiuc.edu/pipermail/llvmdev/2012-July/051434.html).

**Comment by Blei** [comment]
Fixed by commit to main llvm: llvm-mirror/llvm@9e51b14faa55225a3175c4af9c69f5a45dd9a646
