### ISSUE TITLE
Variable access from inline assembler

### ISSUE THREAD

**Issue by SamTechnologeek** [llvm-dcpu16/llvm-dcpu16#195]
Can you actually access variables from inline assembly?

``` c

int main(void)
{
    int bab=2;
    asm("SET A, bab");
    return 0;
}
```

This compiles and assembles properly, but not links:

<pre>
main.o:fake:(.text+0x3): undefined reference to `bab'
</pre>

I'm using latest llvm-dcpu16 version, compiled from source, and latest binutils-dcpu version, compiled from source.

Cheers,
Sam.

**Comment by a1k0n** [comment]
Of course you can, but you need to specify it using the asm syntax.  Here's an example:
https://github.com/a1k0n/tetris-dcpu16/blob/master/crt0.h

The somewhat impenetrable syntax is documented here: http://www.ibiblio.org/gferg/ldp/GCC-Inline-Assembly-HOWTO.html
