### ISSUE TITLE
Fix relative offsets (we have word-addressable memory)

### ISSUE THREAD

**Issue by krasin** [llvm-dcpu16/llvm-dcpu16#34]
Currently, the compiler thinks that the memory is byte-addressable, which cause to the following code:

```
SET [4+SP], X ; The Notch order
SET [2+SP], Y ; The Notch order
SET [0+SP], Z ; The Notch order
```

We use only even offsets, but definitely want to use odd offsets as well:

```
SET [2+SP], X ; The Notch order
SET [1+SP], Y ; The Notch order
SET [0+SP], Z ; The Notch order
```

**Comment by Blei** [comment]
Copying from [here](https://github.com/arbaal/llvm-dcpu16/issues/1):

LLVM/Clang are right now handling the addressing with a byte sized char. Changing the addressing to a word need extensive code rewrites in LLVM and Clang.

For reference:
- http://clang-developers.42468.n3.nabble.com/Re-targeting-clang-to-a-new-architecture-td761920.html
- http://old.nabble.com/Non-standard-byte-sizes-td30786023.html

**Comment by krasin** [comment]
Let's leave this issue aside for some time. Other changes are fairly important and will likely to interfere with this one.

I expect that this issue will be hard to resolve properly, but it probably worth the effort, because this feature looks to be quite desirable for some real-world architectures.

**Comment by ghost** [comment]
The first thread Blei posted contains a patch somebody allready did some time ago.

**Comment by krasin** [comment]
It may help to identify some places where the code assumes sizeof(char) == 8 bits, but that patch is against r102000, which is really-really old.

**Comment by ghost** [comment]
Why don't we adjust the ASMPrinter for now and let the printOperand method print out every (memory location) / 2? That should be relatively save for the ASMPrinter itself, since we are right now only handling word sizes types.

**Comment by krasin** [comment]
We can, especially when you have [fixed](https://github.com/krasin/llvm-dcpu16/commit/51359f12e6499862f88b791412ff6d3a73439fd2#L0R148) the alignment of functions.

I am currently focused on fixing setcc lowering.

**Comment by ghost** [comment]
I have wrote enough code for today, but will make that change tomorrow then.

(Read as: If I code more today, I will produce only garbage...)

**Comment by krasin** [comment]
super, thanks!
