### ISSUE TITLE
Arch Linux: Cmake fails at configuring

### ISSUE THREAD

**Issue by mxrth** [llvm-dcpu16/llvm-dcpu16#43]
cmake .. fails with 
CMake Error at CMakeLists.txt:300 (message):
  Unexpected failure executing llvm-build: Traceback (most recent call last):

```
File "/home/drak3/projects/llvm-dcpu16/utils/llvm-build/llvm-build", line 3, in <module>
  import llvmbuild
File "/home/drak3/projects/llvm-dcpu16/utils/llvm-build/llvmbuild/__init__.py", line 1, in <module>
  from main import main
```

  ImportError: No module named main

-- Configuring incomplete, errors occurred

Full output is at: http://pastebin.com/mYQ5nJJk

**Comment by mxrth** [comment]
Seems to be a problem with my system... Building on a virtual Linux Mint instead of my arch-linux works like a charm

**Comment by krasin** [comment]
Unfortunately, this is a known issue with LLVM and Arch Linux. See, for instance, 

https://bbs.archlinux.org/viewtopic.php?id=133509

To be honest, I don't know how this should be fixed.

**Comment by mxrth** [comment]
Ok the the error is raised because the python command points to python3 which seems to be not supported. The only fix i found so far is temporary symlinking /usr/bin/python to /usr/bin/python2 while building. Somewhat hacky but it works... so i'm closing this issue.
Should i add a entry about this "fix" in the README ? Or is there a nicer way to teach cmake the right python version? (did just some quick googleing)

**Comment by krasin** [comment]
drak3, could you please try to build LLVM + Clang with configure/make?

The process is the following (assuming that you're in the llvm-dcpu16 directory):

```
mkdir build
cd build
../configure --enable-optimized
make -j4
```

Please, let me know if that works for you.

**Comment by krasin** [comment]
@drak3 Could you please help me to test the binary distribution?

Please, find the url and instructions on the [main page](https://github.com/krasin/llvm-dcpu16)

**Comment by Blei** [comment]
Hi everyone, this can be fixed by using cmake like this: `cmake -DPYTHON_EXECUTABLE=/usr/bin/python2 ..`

**Comment by mxrth** [comment]
bulding with configure/make does not work, but Blei's fix works perfectly, i'll add a note to the readme
