### ISSUE TITLE
[debt]Enable section names

### ISSUE THREAD

**Issue by krasin** [llvm-dcpu16/llvm-dcpu16#50]
Currently, printing section names (like .text) are disabled, because DCPU16 assembler do not understand them.

**Comment by krasin** [comment]
Related commit f5a2eac38c30f64d616757fb6cc822c507091806

**Comment by aubreyrjones** [comment]
Okay, so at the risk of sounding like an idiot, what is a reasonable handling of .data and .text sections?

Is the goal to coalesce the data section to a customary region of memory? Is there a reason that memory for symbols should not be allocated where the symbol is defined (walking off string buffers into code leaps to mind)?

I can think of a number of simple compression schemes for saved program image...

**Comment by krasin** [comment]
The primary use of sections on the usual platforms is the ability to mmap different regions with different permissions and share them between different processes, when possible. For example, .text will be shared if two programs from the same image are running, but .data is not.

In our case, we don't have MMU, so the value of sections is close to zero. Feel free to ignore them.

**Comment by aubreyrjones** [comment]
Okay, I see. That's actually what I thought. The whole "my local copy of that .so's data section". Yeah, I'm chucking that.

Please continue to emit them.

I can think of trivial RLE-based compression and things. Especially if there is a big section of, say, "heap" allocated as a global word[1024]. I could literally save 1000 words on disk.

**Comment by ghost** [comment]
Is this debt still valid? I think we enabled all our directives by now!

**Comment by krasin** [comment]
I think you are right.
