### ISSUE TITLE
Unexpected instruction rla.w

### ISSUE THREAD

**Issue by mxrth** [llvm-dcpu16/llvm-dcpu16#60]
When compiling a simple memset implementation a "rla.w Y" instruction is generated.
Compiled sourcecode is here: http://pastie.org/3749550
Generated assembler is here: http://pastie.org/3749552
The rla.w instruction is at line 30
After removing the instruction the code behaves as excepted.

**Comment by ghost** [comment]
Shift operations are a minefield right now.

The EmitShiftInstr() from the DCPU16ISelLowering.cpp needs some serious rework.

**Comment by ghost** [comment]
Fixed.
