### ISSUE TITLE
`JSR __mulhi3hw_noint` emitted in tail-recursive fib implementation

### ISSUE THREAD

**Issue by tylerkahn** [llvm-dcpu16/llvm-dcpu16#61]
Sorry, I don't exactly know what that means, but it's not defined anywhere in the generated assembly file so I assume it's a stub from somewhere.

This was compiled as per the instructions on commit c54c5e722fe23926517056a23e54e29fecbc1cb5

I'm on OS X Lion, x86_64.

Here is the C program I compiled with `bin/clang -ccc-host-triple dcpu16 -S simple.c -o simple.s`

```
int fib(int, int);

int main() {
    return fib(5, 1);
}

int fib(int n, int acc) {
     if (n == 1 || n == 0)
         return acc;
     else
          return fib(n - 1, n * acc);
}     
```

**Comment by ghost** [comment]
Not implemented yet. I will write a patch.

**Comment by tylerkahn** [comment]
Thanks!

**Comment by krasin** [comment]
all credits go to @arbaal
