### ISSUE TITLE
Find a place to coordinate short-term development

### ISSUE THREAD

**Issue by ghost** [llvm-dcpu16/llvm-dcpu16#66]
As I see right now, we have multiple developers who want to constribute to the LLVM-DCPU16 project. I suggest that we find a way for fast, short term communication, since the issue tracker of Github is not that great for that purpose.

How about a Google Groups channel? 
http://groups.google.com/group/llvm-dcpu16-dev

**Comment by mxrth** [comment]
good idea :) joined.

**Comment by krasin** [comment]
joined

**Comment by ghost** [comment]
Can we somehow announce this channel? Probably in the README?

**Comment by krasin** [comment]
Good idea. Feel free to put a note there.
