### ISSUE TITLE
Allow all-memory and memory-literal ops

### ISSUE THREAD

**Issue by krasin** [llvm-dcpu16/llvm-dcpu16#67]
In the generated assembly from fib.c example, there're the following suboptimal code:

```
SET  J, [4+C] ; The Notch order
ADD  J, 1 ; The Notch order
SET  [4+C], J ; The Notch order
```

DCPU-16 capable to work with both memory-literal ops, like:

```
ADD [1+X], 2
```

and all-memory ops like:

```
ADD [1+X], [2+Y]
```

It would be nice to support them.

**Comment by Blei** [comment]
This seems to be working already, just not enabled with -O1. When compiling with -O2, the following program:

``` c
void inc(int *x) {
  *(x+1) = *(x+2);
}
```

compiles to:

```
:inc
        SET     [2+A], [4+A] ; The Notch order
        SET PC, POP ; The Notch order
```

**Comment by krasin** [comment]
Thanks for pointing this out. Apparently, I have adopted a [https://github.com/krasin/llvm-dcpu16/blob/6f17d4a8bcf86d67c3e09ecf2962145f03a1c353/test/CodeGen/DCPU16/Inst16mm.ll](proper test from MSP430 just yesterday), but I have just realized that.
