### ISSUE TITLE
Code generation is broken ATM

### ISSUE THREAD

**Issue by ghost** [llvm-dcpu16/llvm-dcpu16#72]
I forgot to do a "make install" while testing my changed and the build is right now broken. (You can't compile any C-Code)

I will hunt the culpid down.

**Comment by krasin** [comment]
No problem.

FYI: my laptop is so slower than the failed desktop, so I can have a compiled LLVM+Clang with recently pulled changed only once per 40 minutes or so. It kills my productivity. I will go fixing the desktop instead. :(
