### ISSUE TITLE
Adopt MSP430 tests to DCPU16

### ISSUE THREAD

**Issue by krasin** [llvm-dcpu16/llvm-dcpu16#85]
We need to adopt tests from test/CodeGen/MSP430 to test/CodeGen/DCPU16.

**Comment by krasin** [comment]
Inst16rr.ll added in e5387d8bfeba9a18b5a8c660cffb349c0f710d87 (XFAIL for now)

**Comment by krasin** [comment]
Inst16.rr.ll enabled in 2b6dda6bba5c19c06c3bdb18ce5a675331a4392f

**Comment by ghost** [comment]
Fixed by 1c9e9e553f0b2014d766c68c516a1959d37557e6
