### ISSUE TITLE
DCPU16 "features" to consider when implementing

### ISSUE THREAD

**Issue by ghost** [llvm-dcpu16/llvm-dcpu16#87]
Read the section 'Signed Arithmetic' and 'Overflow':

http://fail0verflow.com/blog/2012/dcpu-16-review.html

**Comment by krasin** [comment]
Yes, I've seen that few hours ago.

I agree on signed arithmetic but still not convinced on "Thus, code size (and execution time) is proportional to the number of words to add, squared. Subtraction, of course, has the same issue" for long addition.

**Comment by ghost** [comment]
But still he addressed some valid point. I hope that notch will fix some of the issues, and I fear that we will have to make char 16 bits wide ...

**Comment by krasin** [comment]
Anyway, let's wait for the updates in the DCPU specs.

**Comment by ghost** [comment]
Notch twittered two hours ago that he will update the specs "later". He's even aware of the blog entry above and will consider it. Okay, time to go to work.

**Comment by krasin** [comment]
Have a good day.

I will probably make 2-3 minor updates before going sleep.

**Comment by ghost** [comment]
Fixed by the newest specs.
