### ISSUE TITLE
[debt] Properly implement bit and compare operations

### ISSUE THREAD

**Issue by krasin** [llvm-dcpu16/llvm-dcpu16#93]
Currently, bit tests and comparisons operations pretend to be a single instruction, but they are not. Instead, they generate a text snippet. This makes it impossible to optimize code like:

```
IFN A, B ; First two lines are generated from icmp
SET O, 1
SET A, O ; And this is a plain mov
```

If I understand correctly, it's possible to specify such a snippet as DAG and the optimizer will take care of some of these cases.

**Comment by ghost** [comment]
The referenced issues have been closed. @krasin is this issue still valid?

**Comment by krasin** [comment]
I think we can close this one.
